RETRIEVE = "retrieve"
GRADE_DOCUMENTS = "grade_documents"
GENERATE = "generate"
WEBSEARCH = "websearch"
WEB_SEARCH_DISABLED_NOTICE = "web_search_disabled_notice"
MAX_RETRIES_NOT_GROUNDED_NOTICE = "max_retries_not_grounded_notice"
MAX_RETRIES_NOT_USEFUL_NOTICE = "max_retries_not_useful_notice"
ADD_GROUNDING_FEEDBACK = "add_grounding_feedback"
REWRITE_QUERY = "rewrite_query"
BUDGET_EXHAUSTED_NOTICE = "budget_exhausted_notice"

# Values for GraphState["stop_reason"] ("" = normal finish).
STOP_REASON_WEB_SEARCH_DISABLED = "web_search_disabled"
STOP_REASON_MAX_RETRIES_NOT_GROUNDED = "max_retries_not_grounded"
STOP_REASON_MAX_RETRIES_NOT_USEFUL = "max_retries_not_useful"
STOP_REASON_BUDGET_EXHAUSTED = "budget_exhausted"